export ZSH=$HOME/.oh-my-zsh

TERM='xterm-256color'

ZSH_THEME="robbyrussell"

plugins=(git symfony2)

source $ZSH/oh-my-zsh.sh

alias ducks='du -cksh * | sort -hr | head -n 15'

alias vim=nvim
alias vi=nvim
