---
- name: install apt-transport-https, ca-certificates
  apt:
    name: "{{item}}"
    update_cache: yes
    install_recommends: no
  with_items:
  - apt-transport-https
  - ca-certificates
  become : yes
  become_method: sudo
  
- name: add the new GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become : yes
  become_method: sudo

- name: template a sources.list
  template:
    src: common/files/docker.list
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
  become : yes
  become_method: sudo

- name: install the recommended packages
  apt:
    name: linux-image-extra-virtual
    update_cache: yes
    install_recommends: no
  become : yes
  become_method: sudo

- name: install docker 
  apt:
    name: docker-engine 
    update_cache: yes
    install_recommends: no
  become : yes
  become_method: sudo

- group:
    name: docker
    state: present
  become : yes
  become_method: sudo

- name: add users to the docker group
  user: name=steven groups=docker append=yes
  become : yes
  become_method: sudo
