---
- name: add inkscape ppa
  apt_repository:
    repo: 'ppa:inkscape.dev/trunk'
    state: present
    update_cache: yes
  become : yes
  become_method: sudo

- name: install inkscape
  apt: 
    name: inkscape
    update_cache: yes
  become : yes
  become_method: sudo
