---
- name: install emacs
  apt: 
    name: emacs
    update_cache: yes
  become : yes
  become_method: sudo

- name: install spacemacs 
  git:
    repo: "https://github.com/syl20bnr/spacemacs"
    dest: "~/.emacs.d"
    clone: yes
    force: no

- name: spacemacs config
  copy:
    src: common/files/spacemacs
    dest: "~/.spacemacs"
    mode: 0755
