---
- name: add zeal ppa
  apt_repository:
    repo: 'ppa:zeal-developers/ppa'
    state: present
    update_cache: yes
  become : yes
  become_method: sudo

- name: install zeal
  apt: 
    name: zeal
    update_cache: yes
  become : yes
  become_method: sudo
